resilience4j.circuitbreaker:
  instances:
    paymentService:
      failure-rate-threshold: 50
      ring-buffer-size-in closed-state: 5
      ring-buffer-size-in-half-open-state: 3
      wait-duration-in-open-state: 60s
      automatic-transition-from-open-to-half-open-enabled: true